test

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -16,8 +16,11 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install pytest pytest-cov pylint black pdoc3
+          pip install pytest pytest-cov pylint black
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          if ! pip install pdoc3; then
+            echo "pdoc3 installation failed. Verify compatibility with Python version 3.10."
+          fi
           
       - name: Run tests
         run: make test
